---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: vultr-cr-credentials
  namespace: minikraken-dot-com
spec:
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        envSlug: prod
        projectSlug: projects-mb-pz
        secretsPath: /minikraken-dot-com
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: vultr-cr-credentials
      secretNamespace: minikraken-dot-com
      creationPolicy: "Owner"
      secretType: "kubernetes.io/dockerconfigjson"
      template:
        includeAllSecrets: false
        data:
          .dockerconfigjson: "{{ .REGISTRY_DOCKER_CONFIG_JSON.Value }}"