export { U as default } from './shared/svelte-scoped.v5kEsLox.js'
import 'node:process'
import '@unocss/core'
import '@unocss/preset-uno'
import '@unocss/config'
import 'magic-string'
import 'css-tree'
