import { type Plugin, type ResolvedConfig } from 'vite'
import matter from 'gray-matter'
import path from 'node:path'
import { mkdir, writeFile, exists } from 'node:fs/promises'

export type LocalizedString = {
	en: string
	nl: string
}

export type PostFrontmatter = {
	title: LocalizedString
	date: string
	updated: string
	excerpt: LocalizedString
	author: string
	coverImage: string
	categories: string[]
	tags: string[]
	draft: boolean
}

export type BlogPost = PostFrontmatter & {
	slug: string
	page: string
}

const parseDate = (dateString: string) => {
	const [day, month, year] = dateString.split('/')

	return new Date(Number(year), Number(month) - 1, Number(day)).getTime()
}

const generateBlogPostsFile = async (config: ResolvedConfig) => {
	const blogDirectory = path.resolve(config.root, 'src/routes/(web)/blog')
	const outputFile = path.resolve(config.root, 'src/lib/data/blogposts.ts')
	const glob = new Bun.Glob('*/+page.{svx,md}')

	const posts: BlogPost[] = []

	for await (const file of glob.scan({ cwd: blogDirectory, onlyFiles: true })) {
		const fullPath = path.join(blogDirectory, file)
		const rawContent = await Bun.file(fullPath).text()

		const { data } = matter(rawContent) as unknown as { data: PostFrontmatter }

		if (data.draft) continue

		const slug = path.dirname(file).replaceAll('\\', '/')

		posts.push({
			slug,
			page: `/blog/${slug}`,
			...data
		})
	}

	posts.sort((a, b) => {
		return parseDate(b.date) - parseDate(a.date)
	})

	const contents = `
	// This file is generated by vite-plugin-blog-metadata. Do not edit manually.
	export const posts = ${JSON.stringify(posts)} as const
	`

	if (!(await exists(path.dirname(outputFile)))) {
		await mkdir(path.dirname(outputFile), { recursive: true })
	}
	await writeFile(outputFile, contents)
}

export function blogMetadata(): Plugin {
	let config: ResolvedConfig

	return {
		name: 'vite-plugin-blog-metadata',

		configResolved(resolvedConfig) {
			config = resolvedConfig
		},

		async buildStart() {
			await generateBlogPostsFile(config)
		},

		async handleHotUpdate({ file, server }) {
			const blogDirectory = path.resolve(config.root, 'src/routes/(web)/blog')

			if (!file.startsWith(blogDirectory)) return

			if (!file.endsWith('+page.md') && !file.endsWith('+page.svx')) return

			await generateBlogPostsFile(config)

			const module = server.moduleGraph.getModuleById(
				path.resolve(config.root, 'src/lib/data/blogposts.ts')
			)

			if (module) {
				server.moduleGraph.invalidateModule(module)
			}
		}
	}
}
