name: Build Application

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        # Repository name with owner. For example, actions/checkout
        #repository: https://github.com/MiniKrakenIT/minikraken.com/
        #token: # optional, default is ${{ github.token }}
        fetch-depth: 0 # optional, default is 1
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Get the version
      run: |
        export version=$(release-it --release-version)
        echo "VERSION=${version}" >> $GITHUB_ENV
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
    - name: Build docker image
      uses: docker/build-push-action@v6.2.0
      with:
        file: ./.deployment/Dockerfile
        context: .
        push: true
        #sbom: # optional
        tags: minikraken/private:minikraken-${{ env.VERSION }}
        cache-from: type=registry,ref=minikraken/private:buildcache-minikraken
        cache-to: type=registry,ref=minikraken/private:buildcache-minikraken,mode=max
    #- name: release-it Action
    #  uses: JoshuaKGoldberg/release-it-action@v0.2.3
    #  with:
    #    git-user-email: ${{GITHUB_ACTOR}}@users.noreply.github.com
    #    git-user-name: ${{GITHUB_ACTOR}}
    #    github-token: ${{GITHUB_TOKEN}}

