name: Build Application

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
      #todo add back git config for release-it
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Get the version
      run: |
        export version=$(bunx release-it --release-version)
        echo "VERSION=${version}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build docker image
      uses: docker/build-push-action@v6.2.0
      with:
        file: ./.deployment/Dockerfile
        context: .
        push: true
        #sbom: # optional
        tags: minikraken/private:minikraken-${{ env.VERSION }}
        cache-from: type=repository,ref=minikraken/private:minikraken-cache-${{ env.VERSION }}
        cache-to: type=repository,ref=minikraken/private:minikraken-cache-${{ env.VERSION }},mode=max,compression=zstd
