name: Build Application

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      attestations: none
      checks: none
      #contents:
      deployments: none
      discussions: none
      id-token:	none
      issues: none
      packages:	none
      pages: none
      #pull-requests:
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: git config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Get the version
      run: |
        export version=$(bun run release:version)
        echo "version=${version}" >> $GITHUB_ENV
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
    - name: Build docker image
      uses: docker/build-push-action@v6.2.0
      with:
        file: ./.deployment/Dockerfile
        context: .
        push: true
        #sbom: # optional
        tags: minikraken/private:minikraken-$version
    - name: release-it Action
      uses: JoshuaKGoldberg/release-it-action@v0.2.3
      with:
        git-user-email: ${{GITHUB_ACTOR}}@users.noreply.github.com
        git-user-name: ${{GITHUB_ACTOR}}
        github-token: ${{GITHUB_TOKEN}}

