name: Test

on:
  pull_request:
    branches:
      - main
#      - release/*
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read & write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        path: |
          node_modules/
          .svelte-kit/
        key: minikraken-cache  
    - name: git config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Get the version
      run: |
        bun install --frozen-lockfile
        export VERSION=$(bunx release-it --release-version)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Build application
      run: bun run build
    - name: Deploy new version
      uses: peter-evans/repository-dispatch@v3.0.0
      with:
        repository: MiniKrakenIT/infrastructure
        event-type: deploy-version
        client-payload: '{"application": "Minikraken", "environment": "development", "version": "${{ env.VERSION }}"}'
    
